baseURL = 'https://kukulam.github.io'
languageCode = 'en-us'
title = 'Miłosz Kukuła dev blog'
theme = 'loveit'

[author]
  name = "kukulam"
  email = "kukula.milosz@gmail.com"
  link = "/about"

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    pre = ""
    post = ""
    name = "Posts"
    url = "/posts/"
    title = "Posts"
  [[menu.main]]
    weight = 2
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "trainings"
    pre = ""
    post = ""
    name = "Trainings"
    url = "/trainings"
    title = "Trainings"
#   [[menu.main]]
#     weight = 4
#     identifier = "categories"
#     pre = ""
#     post = ""
#     name = "Categories"
#     url = "/categories/"
#     title = "Categories"
  [[menu.main]]
    weight = 5
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = "Tags"

[params.header]
  desktopMode = "fixed"
  mobileMode = "auto"
[params.header.title]
  logo = ""
  name = "Miłosz Kukuła - dev blog"
  pre = ""
  post = ""
  typeit = false

[params.page.seo]
  images = []
  [params.page.seo.publisher]
    name = "Miłosz Kukuła"
    logoUrl = "/images/avatar.png"

[params.home.profile]
  enable = true
  gravatarEmail = "kukula.milosz@gmail.com"
  avatarURL = "/images/avatar.png"
  title = ""
  subtitle = "clouds, databases, kubernetes, terraform, jvm, go"
  typeit = true
  social = true
  disclaimer = ""

[params.social]
  GitHub = "kukulam"
  Linkedin = "kukulam"
  Instagram = "kukulam.dev"
  Email = "kukula.milosz@gmail.com"
  RSS = false

[params.page.share]
  enable = true
  Twitter = true
  Facebook = false
  Linkedin = true
  HackerNews = false
  Line = false
  Weibo = false


[params]
  defaultTheme = "auto"
  title = "Miłosz Kukuła dev blog"
  description = "Blog for programmers, devOps and secOps engineers"

  [params.app]
    title = "Miłosz Kukuła dev blog"

[params.page.code]
  copy = true
  maxShownLines = 50

[markup]
  [markup.highlight]
    noClasses = false
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6

[params.analytics]
  enable = true

[params.analytics.google]
  id = "G-DQBYFEBSP1"
  anonymizeIP = true

[params.page.comment]
  enable = true

[params.page.comment.disqus]
  enable = true
  shortname = "kukulam.dev"




